version: "3"

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: containerlaravel
    ports:
      - 8083:80
    depends_on:
      - db
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:5.7.30
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "alfa"
    ports:
      - "3307:3306"
